name: Tests
on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - uses: reviewdog/action-rubocop@v2

  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - uses: reviewdog/action-brakeman@v1

  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - uses: reviewdog/action-misspell@v1
        with:
          locale: "US"

  test-rails:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          ## test against supported ruby versions
          ##
          ## cf https://endoflife.date/ruby
          - 2.7.7
          - 3.0.5
          - 3.1.3
          - 3.2.1
        rails:
          ## test against supported rails versions
          ## when updating, be sure to add the matching version Gemfile to
          ## .github/gemfiles
          ##
          ## cf https://endoflife.date/rails
          - 6.0.6.1
          - 6.1.7.2
          # - 7.0.4.2
        include:
          - rails: 6.0.6.1
            ruby: 2.7.7
          - rails: 6.0.6.1
            ruby: 3.0.5
        exclude: []
          ## be careful with which versions of ruby does rails support
          ## cf https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html

    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ github.workspace }}/.github/gemfiles/rails-${{ matrix.rails }}.Gemfile

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Prepare database
        run: bundle exec rails db:setup
      - name: Run tests
        run: bundle exec rake spec
