name: Tests
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          ## test against ruby versions from the last two release cycles
          ## cf https://endoflife.date/ruby
          # 2021-04-05 releases
          - 2.5.9
          - 2.6.7
          - 2.7.3
          - 3.0.1
          # 2021-07-07 releases
          - 2.6.8
          - 2.7.4
          - 3.0.2
        rails:
          ## test against last two releases from supported rails versions
          ## cf https://endoflife.date/rails
          # 2021-05-06 releases
          - 5.2.4.6
          - 5.2.6
          - 6.0.3.7
          - 6.1.3.2
          # 2021-08-20 releases
          - 6.1.4.1
          - 6.0.4.1

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup environment
        run: |
          gem install -v ${{ matrix.rails }} rails;
          bundle install
      - name: Prepare database
        run: bundle exec rails db:setup
      - name: Run tests
        run: bundle exec rake spec
